import type { Zone } from './zones';

// Candidate semantic zones for the 96x72 Qinglan Fangshi blockout.
// They are intentionally separate from ZONES until the map replaces or joins the default world.
export const QINGLAN_FANGSHI_ZONES: Zone[] = [
  {
    zoneId: 'market_west_gate',
    name: '坊市西门',
    kind: 'market_gate',
    bounds: { x1: 4, y1: 16, x2: 20, y2: 25 },
    entryPoints: [{ x: 8, y: 20 }, { x: 18, y: 20 }],
    allowedActions: ['talk', 'gift', 'spar'],
    dangerLevel: 0,
    spiritualEnergy: 1,
    description: '青岚坊市西侧入口，连接回宗门的山路。守卫与宗门弟子常在此往来。',
  },
  {
    zoneId: 'market_medicine_shop',
    name: '灵药铺',
    kind: 'medicine_shop',
    bounds: { x1: 21, y1: 27, x2: 36, y2: 32 },
    entryPoints: [{ x: 35, y: 30 }, { x: 35, y: 31 }],
    allowedActions: ['talk', 'trade', 'gift', 'steal'],
    dangerLevel: 1,
    spiritualEnergy: 2,
    description: '北街灵药铺门前，可买卖丹药、草药，也容易引出偷药与欠账传闻。',
  },
  {
    zoneId: 'market_inn',
    name: '散修客栈',
    kind: 'inn',
    bounds: { x1: 55, y1: 26, x2: 66, y2: 31 },
    entryPoints: [{ x: 58, y: 28 }, { x: 62, y: 30 }],
    allowedActions: ['talk', 'trade', 'gift'],
    dangerLevel: 1,
    spiritualEnergy: 1,
    description: '坊市北街的客栈门前，散修、商队与外来消息常在此停留。',
  },
  {
    zoneId: 'market_main_street',
    name: '河街主市',
    kind: 'market',
    bounds: { x1: 38, y1: 32, x2: 56, y2: 41 },
    entryPoints: [{ x: 43, y: 36 }, { x: 52, y: 38 }],
    allowedActions: ['talk', 'trade', 'gift', 'steal'],
    dangerLevel: 1,
    spiritualEnergy: 1,
    description: '青岚坊市最热闹的河街主市，摊贩、人流与日常交易集中于此。',
  },
  {
    zoneId: 'market_tea_stall',
    name: '坊市茶摊',
    kind: 'tea_stall',
    bounds: { x1: 30, y1: 50, x2: 63, y2: 55 },
    entryPoints: [{ x: 56, y: 53 }, { x: 60, y: 54 }],
    allowedActions: ['talk', 'gift', 'spar', 'cultivate', 'request_teaching', 'breakthrough'],
    dangerLevel: 0,
    spiritualEnergy: 1,
    description: '临河茶摊旁的清静空地，适合打听传闻、赠礼、切磋、吐纳、请教前辈与小心冲关。',
  },
  {
    zoneId: 'market_dock',
    name: '货船码头',
    kind: 'dock',
    bounds: { x1: 69, y1: 47, x2: 92, y2: 55 },
    entryPoints: [{ x: 76, y: 55 }, { x: 78, y: 51 }],
    allowedActions: ['talk', 'trade', 'steal'],
    dangerLevel: 2,
    spiritualEnergy: 1,
    description: '东南货船码头，外来货物与灰色交易的边缘地带。',
  },
  {
    zoneId: 'market_east_road',
    name: '东坊路',
    kind: 'town_road',
    bounds: { x1: 74, y1: 24, x2: 88, y2: 38 },
    entryPoints: [{ x: 78, y: 33 }, { x: 83, y: 35 }],
    allowedActions: ['talk', 'travel'],
    dangerLevel: 0,
    spiritualEnergy: 1,
    description: '通往山下镇方向的东坊路，暂作为大城镇接口。',
  },
];
